config/routes.rb
Rails.application.routes.draw do
  resources :car_places
  resources :places
  resources :cars
  resources :owners
  resources :owner_types

end

app/models/car_place.rb
class CarPlace < ActiveRecord::Base
  belongs_to :car
  belongs_to :place
end

app/controllers/car_places_controller.rb
class CarPlacesController < ApplicationController
  before_action :set_car_place, only: [:show, :edit, :update, :destroy]

  # GET /car_places
  # GET /car_places.json
  def index
    @car_places = CarPlace.all
  end

  # GET /car_places/1
  # GET /car_places/1.json
  def show
  end

  # GET /car_places/new
  def new
    @car_place = CarPlace.new
  end

  # GET /car_places/1/edit
  def edit
  end

  # POST /car_places
  # POST /car_places.json
  def create
    @car_place = CarPlace.new(car_place_params)

    respond_to do |format|
      if @car_place.save
        format.html { redirect_to @car_place, notice: 'Car place was successfully created.' }
        format.json { render :show, status: :created, location: @car_place }
      else
        format.html { render :new }
        format.json { render json: @car_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_places/1
  # PATCH/PUT /car_places/1.json
  def update
    respond_to do |format|
      if @car_place.update(car_place_params)
        format.html { redirect_to @car_place, notice: 'Car place was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_place }
      else
        format.html { render :edit }
        format.json { render json: @car_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_places/1
  # DELETE /car_places/1.json
  def destroy
    @car_place.destroy
    respond_to do |format|
      format.html { redirect_to car_places_url, notice: 'Car place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_place
      @car_place = CarPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_place_params
      params.require(:car_place).permit(:hora_entrada, :hora_salida, :fecha_entrada, :fecha_salida, :car_id, :place_id)
    end
end

app/helpers/car_places_helper.rb
module CarPlacesHelper
end

app/views/car_places/_form.html.erb
<%= form_for(@car_place) do |f| %>
  <% if @car_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_place.errors.count, "error") %> prohibited this car_place from being saved:</h2>

      <ul>
      <% @car_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hora_entrada %><br>
    <%= f.time_select :hora_entrada %>
  </div>
  <div class="field">
    <%= f.label :hora_salida %><br>
    <%= f.time_select :hora_salida %>
  </div>
  <div class="field">
    <%= f.label :fecha_entrada %><br>
    <%= f.date_select :fecha_entrada %>
  </div>
  <div class="field">
    <%= f.label :fecha_salida %><br>
    <%= f.date_select :fecha_salida %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.text_field :car_id %>
  </div>
  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.text_field :place_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/car_places/edit.html.erb
<h1>Editing Car Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @car_place %> |
<%= link_to 'Back', car_places_path %>

app/views/car_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Car Places</h1>

<table>
  <thead>
    <tr>
      <th>Hora entrada</th>
      <th>Hora salida</th>
      <th>Fecha entrada</th>
      <th>Fecha salida</th>
      <th>Car</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_places.each do |car_place| %>
      <tr>
        <td><%= car_place.hora_entrada %></td>
        <td><%= car_place.hora_salida %></td>
        <td><%= car_place.fecha_entrada %></td>
        <td><%= car_place.fecha_salida %></td>
        <td><%= car_place.car %></td>
        <td><%= car_place.place %></td>
        <td><%= link_to 'Show', car_place %></td>
        <td><%= link_to 'Edit', edit_car_place_path(car_place) %></td>
        <td><%= link_to 'Destroy', car_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car place', new_car_place_path %>

app/views/car_places/new.html.erb
<h1>New Car Place</h1>

<%= render 'form' %>

<%= link_to 'Back', car_places_path %>

app/views/car_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hora entrada:</strong>
  <%= @car_place.hora_entrada %>
</p>

<p>
  <strong>Hora salida:</strong>
  <%= @car_place.hora_salida %>
</p>

<p>
  <strong>Fecha entrada:</strong>
  <%= @car_place.fecha_entrada %>
</p>

<p>
  <strong>Fecha salida:</strong>
  <%= @car_place.fecha_salida %>
</p>

<p>
  <strong>Car:</strong>
  <%= @car_place.car %>
</p>

<p>
  <strong>Place:</strong>
  <%= @car_place.place %>
</p>

<%= link_to 'Edit', edit_car_place_path(@car_place) %> |
<%= link_to 'Back', car_places_path %>